ftp:
  server: ${FTP_SERVER}
  username: ${FTP_USERNAME}
  password: ${FTP_PASSWORD}
  remote_directory: "/BMKG_modified"
  local_directory: "data/raw"

models:
  tilong:
  # General
    name: "tilong"
    dam_id: "177"
    project_path: "data/model/tilong/model_tilong/Model_DAS_Tilong.hms"
    log_file: "logs/tilong_import.log"
    processed_dates_log: "logs/tilong_processed_dates.txt"
    destination: "data/model/tilong/model_tilong/data/ECMWF.dss"

  # Spatial
    clip_shp: "data/model/tilong/clip_tilong/MANIKIN  BAKI_51S.shp"
    basin_shp: "data/model/tilong/basin_tilong/basin_tilong.shp"
    partA: "UTM51S"
    projected_crs: "EPSG:32751"
    targetWkt: 32751

  # Rainfall
    animation_output: "data/output/tilong/animation"
    thiessen_excel: "data/model/tilong/thiessen/tilong.xls"
    thiessen_output: "data/output/tilong/thiessen/"

  # Forecast
    forecast_paths:
      - ["data/model/tilong/model_tilong/forecast/PrediksiECMWF.forecast", "PrediksiECMWF"]
    start_time: "18:00"
    forecast_time: "08:00"
    end_time: "17:00"

  # model2:
  #   log_file: "logs/model2_import.log"
  #   processed_dates_log: "logs/model2_processed_dates.txt"
  #   base_dir: "data/model2"
  #   clip_shp: "data/model2/clip.shp"
  #   destination: "data/model2/output.dss"
  #   targetWkt: 32648
  #   partA: "UTM48N"
  #   basin_shp: "data/model2/basin.shp"
  #   animation_output: "data/model2/animation"


shared:
  raw_folder: "data/raw"
  data_cutoff_time: "12:35"


